apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tomcat
  namespace: argocd
spec:
  project: default
  destination:
    namespace: tomcat
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PruneLast=true
    - CreateNamespace=true
  source:
    chart: tomcat
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: v10.3.9
